name: Welcome New Contributor

on:
 pull_request_target:
  types: [opened]

jobs:
 greet-new-contributor:
  runs-on: ubuntu-latest
  steps:
   - name: Welcome First-Time Contributor
     uses: actions/first-interaction@v1
     with:
       repo-token: ${{ secrets.GITHUB_TOKEN }}
       pr-message: "Thankyou for your first contribution! We're excited to have you here."
     
